import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import yfinance as yf

# ---------------------------------------------------
# Setup
# ---------------------------------------------------
OUTPUT_DIR = "output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("📈 Fetching market data...")
# We use SPY (S&P 500 ETF) as our baseline asset
ticker = "SPY"
raw_data = yf.download(ticker, start="2018-01-01", end="2025-12-31")

# Clean multi-level column index if generated by yfinance
if isinstance(raw_data.columns, pd.MultiIndex):
    raw_data.columns = raw_data.columns.get_level_values(0)

df = raw_data.copy()

# ---------------------------------------------------
# Feature Engineering (Sequence Basics)
# ---------------------------------------------------
print("🛠️ Engineering sequential features...")

# Target Variable: Did the price go UP tomorrow compared to today's close?
df["Target"] = (df["Close"].shift(-1) > df["Close"]).astype(int)

# Feature 1: Daily Return (Momentum)
df["Return"] = df["Close"].pct_change()

# Feature 2: 5-Day Moving Average Tally (Trend)
df["MA_5"] = df["Close"] / df["Close"].rolling(window=5).mean()

# Feature 3: 20-Day Moving Average Tally (Trend)
df["MA_20"] = df["Close"] / df["Close"].rolling(window=20).mean()

# Feature 4: 10-Day Volatility (Standard Deviation of Returns)
df["Vol_10"] = df["Return"].rolling(window=10).std()

# Drop rows with NaN values created by rolling windows and shifting
df.dropna(inplace=True)

# Define feature matrix and target matrix
feature_cols = ["Return", "MA_5", "MA_20", "Vol_10"]
X = df[feature_cols]
y = df["Target"]

# ---------------------------------------------------
# Time Series Split (No Shuffling allowed!)
# ---------------------------------------------------
# CRITICAL CONCEPT: We cannot use standard random train_test_split.
# Doing so would cause "look-ahead bias" (leak future data into the past).
# Instead, we split chronologically.

split_idx = int(len(df) * 0.8)

X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

print(f"Training days: {len(X_train)} | Testing days: {len(X_test)}")

# ---------------------------------------------------
# Feature Scaling
# ---------------------------------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ---------------------------------------------------
# Baseline Model: Logistic Regression
# ---------------------------------------------------
# We use an L2-penalized Logistic Regression model. It acts as an excellent
# baseline because it assumes a simple, linear relationship and limits overfitting.
model = LogisticRegression(random_state=42)
model.fit(X_train_scaled, y_train)

# ---------------------------------------------------
# Evaluation & Predictions
# ---------------------------------------------------
y_train_pred = model.predict(X_train_scaled)
y_test_pred = model.predict(X_test_scaled)
y_train_prob = model.predict_proba(X_train_scaled)[:, 1]

train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

print("\n📊 Stock Movement Prediction Results\n")
print(f"Training Accuracy: {train_acc:.4f}")
print(f"Testing Accuracy (Out-of-Sample): {test_acc:.4f}")
print("\n📝 Out-of-Sample Classification Report:")
print(classification_report(y_test, y_test_pred, zero_division=0))

# ---------------------------------------------------
# Feature Coefficients Analysis
# ---------------------------------------------------
coefficients = model.coef_[0]

plt.figure(figsize=(8, 5))
plt.barh(feature_cols, coefficients, color="teal")
plt.axvline(0, color="black", linestyle="--", linewidth=0.8)
plt.title(f"Logistic Regression Coefficients ({ticker} Baseline)")
plt.xlabel("Coefficient Weight (Directional Impact)")

coef_path = os.path.join(OUTPUT_DIR, "feature_coefficients.png")
plt.savefig(coef_path)
plt.close()
print(f"Saved feature directional analysis to: {coef_path}")

# ---------------------------------------------------
# Visualization: Model Fit Over Time (Training Data)
# ---------------------------------------------------
plt.figure(figsize=(14, 6))

# Grab chronological dates corresponding to our training set
train_dates = df.index[:split_idx]

# Plot a rolling average of actual outcomes vs model probabilities to make the noise scannable
# A 20-day rolling window helps smooth out the 0s and 1s so you can see the true underlying trend
actual_rolling = pd.Series(y_train.values, index=train_dates).rolling(window=20).mean()
pred_rolling = pd.Series(y_train_prob, index=train_dates).rolling(window=20).mean()

plt.plot(train_dates, actual_rolling, label="Actual Up-Day Trend (20-Day MA)", color="black", alpha=0.5)
plt.plot(train_dates, pred_rolling, label="Model Churning Probability (20-Day MA)", color="crimson", linewidth=2)

plt.axhline(0.5, color="blue", linestyle=":", label="Decision Threshold (50%)")
plt.title(f"Baseline Model Predicted Probabilities vs Actual Market Trend (Training Data)")
plt.xlabel("Timeline")
plt.ylabel("Probability / Trend Rate")
plt.legend(loc="upper left")
plt.grid(True, linestyle="--", alpha=0.5)

fit_path = os.path.join(OUTPUT_DIR, "model_training_fit.png")
plt.savefig(fit_path)
plt.close()
print(f"Saved training data visualization to: {fit_path}")

# ---------------------------------------------------
# Business Check: Baseline Cumulative Accuracy Check
# ---------------------------------------------------
# Check market base rate (How often did the market actually go up?)
base_rate = y_test.mean()
print(f"Market actual up-days in test set: {base_rate:.2%}")
print(f"Model prediction hit rate: {test_acc:.2%}")